### ISSUE TITLE
scalafmt fails when using html

### ISSUE THREAD

**Issue by visox** [olafurpg/scalafmt#541] opened 2016-10-22 04:21 UTC
Hi,

i have a problem in my small scala.js project, while using `"com.thoughtworks.binding" %%% "dom" % "10.0.0-M5"`

additional info:
`addSbtPlugin("com.geirsson" %% "sbt-scalafmt" % "0.4.6")`
`scala version 2.11.8`

the problem is i am using html code in scala (see example) and scalafmt is throwing `IncompatibleClassChangeError` 

```
import com.thoughtworks.binding.{Binding, dom}
import com.thoughtworks.binding.Binding.Var
...
import org.scalajs.dom.Event
import org.scalajs.dom.html.Div
...
object Something {

  @dom
  def apply(user: Var[Option[User]], logoutCall: () => Unit): Binding[Div] = {
<div>
{
   user.bind match {
      case None =>
         <div/>
      case Some(_) =>
         <a class = "btn btn-secondary" style = "float:right;" onclick = { (e: Event) ⇒ logoutCall() }>
            Logout
         </a>
     }
   }
</div>
}
```

in terminal
`>`scalafmt
[trace] Stack trace suppressed: run last web-client/compile:scalafmt for the full output.
[error](web-client/compile:scalafmt) java.lang.IncompatibleClassChangeError: Found class fastparse.core.Parser, but interface was expected

`>`last web-client/compile:scalafmt
java.lang.IncompatibleClassChangeError: Found class fastparse.core.Parser, but interface was expected
    at scala.meta.internal.tokenizers.LegacyScanner.getXml(LegacyScanner.scala:959)
    at scala.meta.internal.tokenizers.LegacyScanner.fetchLT$1(LegacyScanner.scala:336)
    at scala.meta.internal.tokenizers.LegacyScanner.fetchToken(LegacyScanner.scala:344)
    at scala.meta.internal.tokenizers.LegacyScanner.nextToken(LegacyScanner.scala:233)
    at scala.meta.internal.tokenizers.LegacyScanner.foreach(LegacyScanner.scala:1022)
    at scala.meta.internal.tokenizers.ScalametaTokenizer.uncachedTokenize(ScalametaTokenizer.scala:154)
    at scala.meta.internal.tokenizers.ScalametaTokenizer.tokenize(ScalametaTokenizer.scala:34)
    at scala.meta.internal.tokenizers.ScalametaTokenizer$$anon$2.apply(ScalametaTokenizer.scala:263)
    at scala.meta.tokenizers.Api$XtensionTokenizeDialectInput.tokenize(Api.scala:23)
    at scala.meta.tokenizers.Api$XtensionTokenizeInputLike.tokenize(Api.scala:12)
    at scala.meta.internal.parsers.ScalametaParser.scannerTokens$lzycompute(ScalametaParser.scala:207)
    at scala.meta.internal.parsers.ScalametaParser.scannerTokens(ScalametaParser.scala:207)
    at scala.meta.internal.parsers.ScalametaParser.<init>(ScalametaParser.scala:168)
    at scala.meta.internal.parsers.ScalametaParser$$anon$201.apply(ScalametaParser.scala:3650)
    at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:21)
    at scala.meta.parsers.Api$XtensionParseInputLike.parse(Api.scala:10)
    at org.scalafmt.Scalafmt$.format(Scalafmt.scala:51)
    at org.scalafmt.cli.Scalafmt210.format(Scalafmt210.scala:46)
    at org.scalafmt.cli.Scalafmt210.format(Scalafmt210.scala:30)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.scalafmt.sbt.HasScalaFmt.org$scalafmt$sbt$HasScalaFmt$$handleFile(HasScalaFmt.scala:85)
    at org.scalafmt.sbt.HasScalaFmt$$anonfun$writeFormattedContentsToFiles$1$$anonfun$apply$3.apply(HasScalaFmt.scala:54)
    at org.scalafmt.sbt.HasScalaFmt$$anonfun$writeFormattedContentsToFiles$1$$anonfun$apply$3.apply(HasScalaFmt.scala:54)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.parallel.immutable.ParHashSet$ParHashSetIterator.foreach(ParHashSet.scala:76)
    at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:975)
    at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:54)
    at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
    at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
    at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:56)
    at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:972)
    at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:165)
    at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:514)
    at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error](web-client/compile:scalafmt) java.lang.IncompatibleClassChangeError: Found class fastparse.core.Parser, but interface was expected

**Comment by olafurpg** [comment] 2016-10-22 18:31
What SBT version are you using?

**Comment by visox** [comment] 2016-10-23 00:52
Hi,
sbt is `0.13.12` and i didn't try it in CLI yet.

**Comment by olafurpg** [comment] 2016-10-23 14:23
Can you try with sbt 0.13.11? I am unable to reproduce with the CLI. I use scalafmt with binding.scala projects as well with no problem.

I suspect this may be related to #485, which is caused by a regression in SBT 0.13.12

**Comment by visox** [comment] 2016-10-24 00:11
i tried, but no obvious change, i have the same error and same stacktrace.

Damn what i am doing wrong :/

**Comment by KadekM** [comment] 2016-10-30 00:04
I am able to reproduce it on `sbt 0.13.13` and `scalafmt 0.4.8`

**Comment by olafurpg** [comment] 2016-10-30 12:20
@KadekM unfortunately, the bug did not get fixed in sbt 0.13.13, please upvote https://github.com/sbt/sbt/issues/2786 to help prioritize the ticket.

**Comment by dwijnand** [comment] 2017-03-02 16:52
I think this can be closed now with never versions of sbt-scalafmt avoiding sbt/sbt#2786.

**Comment by olafurpg** [comment] 2017-03-03 10:31
Please reopen of this is still an issue.

**Closed by olafurpg** 2017-03-03 10:31 UTC
Labels: sbt
