### ISSUE TITLE
Comment breaks wrapping

### ISSUE THREAD

**Issue by dwijnand** [olafurpg/scalafmt#762] opened 2017-03-03 09:16 UTC
- **Version**: 0.5.7
- **Integration**: CLI
- **Configuration**:
```
    style = defaultWithAlign
maxColumn = 112
```

## Unexpected formatting output

Obtained, scalafmt formats code like this:

```scala
lazy val ivyProj = (project in file("ivy"))
  .dependsOn(interfaceProj,
             crossProj,
             logProj % "compile;test->test",
             ioProj  % "compile;test->test", /*launchProj % "test->test",*/ collectionProj)
```

Expected, I would like the formatted output to look like this:
```scala
lazy val ivyProj = (project in file("ivy"))
  .dependsOn(interfaceProj,
             crossProj,
             logProj % "compile;test->test",
             ioProj  % "compile;test->test", /*launchProj % "test->test",*/
             collectionProj)
```

or something along those lines. Basically I expect collectionProj to be on a new line.

**Comment by olafurpg** [comment] 2017-03-03 13:11
This is probably caused by a false assumption that the comment is `//` which forces a newline after itself. I think this can be fixed by replacing some `.is[Comment]` condition with `isInlineComment`, it's possible to track down the line in Router.scala where this happens

**Closed** 2017-03-03 20:03 UTC
Labels: hackathon
