### ISSUE TITLE
scalafmt scaladoc jar empty

### ISSUE THREAD

**Issue by cvogt** [olafurpg/scalafmt#778] opened 2017-03-05 10:11 UTC
This template is a guideline, not a strict requirement.
- **Version**: 0.5.7
- **Integration**: library calls

## Steps

Download and extract http://central.maven.org/maven2/com/geirsson/scalafmt-core_2.11/0.5.7/scalafmt-core_2.11-0.5.7-javadoc.jar

## Problem

There is only a META-INF folder. No scaladoc. This means IntelliJ, https://www.javadoc.io/, Dash, etc cannot find the scaladoc.

## Expectation

publish scaladoc in the -javadoc jar :).

## Workaround

Read the source code on github.

**Comment by olafurpg** [comment] 2017-03-05 10:51
Thanks for reporting! Scaladoc is disabled because of https://github.com/scalameta/paradise/issues/55

Core uses scalameta/paradise macros, so there are no sources included in the doc task https://github.com/olafurpg/scalafmt/blob/e407aea45f2a0ffa2103904981a59e2d04e16f8e/build.sbt#L15 In theory, we could publish scaladoc for everything outside the `config` package.

**Comment by olafurpg** [comment] 2017-03-05 12:38
Duplicate of #463

**Closed by olafurpg** 2017-03-05 12:38 UTC
