### ISSUE TITLE
SBT plugin (0.4.10) injects itself into libraryDependencies

### ISSUE THREAD

**Issue by djspiewak** [olafurpg/scalafmt#596] opened 2016-11-18 20:24 UTC
```
List(org.scala-lang:scala-library:2.10.6, org.scoverage:scalac-scoverage-runtime_2.10:1.1.1:provided, org.scoverage:scalac-scoverage-plugin_2.10:1.1.1:provided, org.scala-lang:scala-library:2.11.8:scalafmt, com.geirsson:scalafmt-cli_2.11:0.4.10:scalafmt, org.scala-lang:scala-compiler:2.10.6:ensime-internal
```

Er?  What?  Notice the scala version mismatch.

This outright *breaks* any 2.10 build.  Also it's incredibly bizarre and doesn't make any sense.  What ends up happening here is the scalafmt-derived scala-library dependency overrides the 2.10.6 dependency, which in turn breaks cross-building… but only partway.  SBT still *thinks* it's doing a 2.10 cross-build, but it will actually build 2.11.  You only notice when you try to push to a Nexus from two different builds (one for each version) and Nexus rejects the redundant 2.11 artifacts.

**Comment by sjrd** [comment] 2016-11-18 20:43
Duplicate of https://github.com/olafurpg/scalafmt/issues/485

Note that this is an sbt issue, not a scalafmt. scalafmt puts itself in the `scalafmt` configuration, which should be independent of `compile`, `test` and all the others. However, sbt 0.13.12 broke this independence.

There's nothing scalafmt can do about this. It needs to be fixed on sbt's side. In the meantime, you can downgrade to sbt 0.13.11 like everyone else.

**Comment by djspiewak** [comment] 2016-11-18 20:50
Even on 0.13.11, this is a problem.  And it is independent of #485, so far as I can tell.  Or at least, another consequence of the same underlying injection.  See the following error:

```
[warn] Binary version (2.11) for dependency org.scala-lang#scala-library;2.11.8
[warn] 	in foo#core_2.10;2.0.0-SNAPSHOT differs from Scala binary version in project (2.10).
[warn] Binary version (2.11) for dependency org.scala-lang#scala-library;2.11.8
[warn] 	in foo#test_2.10;2.0.0-SNAPSHOT differs from Scala binary version in project (2.10).
```

To reproduce that, I ran `++ "2.10.6` followed by `compile` in the sbt shell.

**Comment by olafurpg** [comment] 2016-11-18 22:48
Can you please provide a minimal repo to reproduce this issue on 0.13.11? The sbt plugin has injected a dependency on scalafmt + scala-library into a custom scope since 0.1. The Scala version should be isolated between different scopes but sbt 0.13.12 had a regression that broke that, see https://github.com/sbt/sbt/issues/2786

**Comment by djspiewak** [comment] 2016-11-18 22:50
I'll see what I can do.

BTW, the outright *failure* of the build that I was seeing was actually due to another problem (confusingly, which *also* futzed with the scala version).  After fixing that, I still see the warning I listed, but that warning doesn't appear to actually kill anything.

**Comment by olafurpg** [comment] 2016-11-18 22:59
I admit it's unfortunate we have to resort to this dependency injection hack in the sbt plugin, but sbt offers no better solution for plugins to use 2.11 only libraries. Backporting scalameta to 2.10 has been unsuccessful so far.

**Comment by olafurpg** [comment] 2016-11-20 11:21
Please reopen if you can find a reproduction on 0.13.11.

@djspiewak I want to ask to you please be more friendly in future issues. Opening a ticket with inflammatory statements like

> Er? What? Notice the scala version mismatch.
> This outright breaks any 2.10 build. Also it's incredibly bizarre and doesn't make any sense. 

makes a bad experience for everyone involved in making this OSS project a welcoming environment to learn, teach and contribute.

PS. You might want to consider becoming the sbt plugin maintainer, it's looking for a new custodian #597

**Closed by olafurpg** 2016-11-20 11:21 UTC
Labels: sbt
