### ISSUE TITLE
Binary operator precedence and spaces

### ISSUE THREAD

**Issue by sjrd** [olafurpg/scalafmt#272] opened 2016-05-19 14:42 UTC
Original:
```scala
-    if (iv == value && 1.0/value != Double.NegativeInfinity) iv
+    if (iv == value && 1.0 / value != Double.NegativeInfinity) iv
```
See https://github.com/scala-js/scala-js/blob/master/CODINGSTYLE.md#spaces

**Comment by olafurpg** [comment] 2016-10-23 16:54
Duplicate of #511 (which contains more code examples than this issue).

**Closed by olafurpg** 2016-10-23 16:54 UTC
