### ISSUE TITLE
Update to scalameta 1.0.0

### ISSUE THREAD

**Issue by NicolasRouquette** [olafurpg/scalafmt#392] opened 2016-08-07 00:12 UTC
I have a code generator that uses scalameta 1.0.0; I would like to format the generated source with scalafmt like this:

Original:
```scala
import akka.util.ByteString

object SourceCodeFormatter {

  def format
  (source: scala.meta.Source)
  : ByteString
  = ByteString(org.scalafmt.Scalafmt.format(source.syntax).get)
```

Using:
* 0.2.11
* --style default

At runtime, this fails with an exception:
```
java.lang.NoSuchMethodError: scala.meta.inputs.Input$.stringToInput()Lorg/scalameta/convert/Convert;
	at org.scalafmt.Scalafmt$.format(ScalaFmt.scala:30)
	at org.omg.oti.uml.md18.meta.SourceCodeFormatter$.format(SourceCodeFormatter.scala:49)
```

This seems to be due to a change of API in scalameta between the version used in scalafmt 0.2.11 (i.e. 0.1.0-RC1) and 1.0.0.

**Comment by olafurpg** [comment] 2016-08-07 08:02
Duplicate of #214. See https://gitter.im/olafurpg/scalafmt?at=57a6ead1483751d50f305a4d

**Closed by olafurpg** 2016-08-07 08:02 UTC
