### ISSUE TITLE
Formatting of classes and methods running over the max line length

### ISSUE THREAD

**Issue by lambdista** [olafurpg/scalafmt#449] opened 2016-09-19 11:52 UTC
**Version**: (for example, 0.3.1)

```scala
final case class FooBarBaz(foo: String, bar: Int, baz: Long, ...)
```

Scalafmt:
```scala
// using scalafmt if I format a class whose fields run over the max length the resulting code looks like this:
final case class FooBarBaz(foo: String,
                           bar: Int,
                           baz: Long,
                           ...)
```

I would like the input to look like this:
```scala
final case class FooBarBaz(
    foo: String,
    bar: Int,
    baz: Long,
    ...
)

// Same thing for methods. Result from scalafmt:
def foobarbazfoobarbaz(a: Int, b: String, c: Long, d: String)(implicit I: Int,
                                                              L: Long,
                                                              S: String): String = {
  ???
}

// What about the following?
def fdsffdfdfsfsefsdfdsfdsfdsfdsfdsfdf(
    a: Int,
    b: String,
    c: Long,
    d: String
)(implicit 
    I: Int,
    L: Long,
    S: String
): String = {
  ???
}
```

**Comment by olafurpg** [comment] 2016-09-19 12:12
Try `--style intellij --alignByOpenParenDefnSite false`.

**Comment by lambdista** [comment] 2016-09-19 13:05
Ok, using both it got right the class indentation but for the method I got this one:

```scala
def foobarbazfoobarbaz(
  a: Int,
  b: String,
  c: Long,
  d: String
)(implicit I: Int, L: Long, S: String): String = {
  ???
}
```
From our twitter conversation I understand that this one still needs to be implemented:
```scala
def fdsffdfdfsfsefsdfdsfdsfdsfdsfdsfdf(
    a: Int,
    b: String,
    c: Long,
    d: String
)(implicit 
    I: Int,
    L: Long,
    S: String
): String = {
  ???
}
```

Furthermore, with these settings I got this:
```scala
sealed trait Foo

object Foo {
  case object Alpha extends Foo
  case object Beta extends Foo // PROBLEM: not aligned
}
```
Instead I want this: 
```scala
sealed trait Foo

object Foo {
  case object Alpha extends Foo
  case object Beta   extends Foo // aligned
}
```
So I'd like to have the features of `--style defaultWithAlign` with just the behaviour of `--style intellij --alignByOpenParenDefnSite false` for classes and methods. Is there a way to do that?

**Comment by olafurpg** [comment] 2016-09-19 13:12
The following example is on a single line because it can fit on a single line.

```scala
)(implicit I: Int, L: Long, S: String): String = {
```

There's no way to force config style with --danglingParentheses true (which --style intellij uses) so you're stuck with that, I'm sorry.


This style

```scala
(implicit 
    I: Int,
    L: Long,
    S: String
): String = {
```

probably belongs in a separate issue. I think we'll treat it like regular config style argument lists.
 
You can replace --style intellij  with the settings it defines:
https://github.com/olafurpg/scalafmt/blob/master/core/src/main/scala/org/scalafmt/ScalafmtStyle.scala#L245

Apply those settings after --style defaultWithAlign and you can enjoy all the goodies : )

**Comment by lambdista** [comment] 2016-09-19 13:17
Thank you, tried this but got a config parse error:
```
--style defaultWithAlign
--maxColumn 120
--alignByOpenParenDefnSite false
--continuationIndentCallSite 2
--continuationIndentDefnSite 2
--alignByOpenParenCallSite false
--configStyleArguments false
--danglingParentheses true
```

**Comment by olafurpg** [comment] 2016-09-19 13:25
Try running it with the CLI, it should print out the culprit flag.

**Comment by olafurpg** [comment] 2016-09-19 13:26
The names of the flags that the CLI supports are listed here: https://olafurpg.github.io/scalafmt/#Usageexamples

**Comment by olafurpg** [comment] 2016-09-19 13:26
Try dropping the configStyleArguments line.

**Comment by lambdista** [comment] 2016-09-19 13:35
Great! Thank you so much.

**Comment by olafurpg** [comment] 2016-09-27 21:37
@lambdista Am I free to close this issue?

**Comment by lambdista** [comment] 2016-09-28 07:50
Oh sorry, I'll close it. Thank you for your support.

**Comment by lambdista** [comment] 2016-10-19 11:29
Updated to 0.4.7, using the following .scalafmt.conf:
```
style =  defaultWithAlign
maxColumn = 80
align.openParenDefnSite = false
continuationIndent.callSite = 2
continuationIndent.defnSite = 2
align.openParenCallSite = false
danglingParentheses = true
```
 I formatted the following class:
```scala
final case class Foo(alpha: String, beta: String, gamma: String, bar: String, baz: String)
```

The result I obtained is:
```scala
final case class Foo(
  alpha: String,
  beta: String,
  gamma: String,
  bar: String,
  baz: String)
```
If I use scalafmt version 0.3.1 and .scalafmt as follows:
```
--style defaultWithAlign
--maxColumn 80
--alignByOpenParenDefnSite false
--continuationIndentCallSite 2
--continuationIndentDefnSite 2
--alignByOpenParenCallSite false
--danglingParentheses true
```
then the result of the same class is the following:
```scala
final case class Foo(
  alpha: String,
  beta: String,
  gamma: String,
  bar: String,
  baz: String
)
```
which is what I'd like to have. 

A regression?

**Comment by olafurpg** [comment] 2016-10-23 14:38
@lambdista I was able to reproduce and tracked it down to an undocumented changed in how dangling parentheses is parsed. Prior to 0.4, --danglingParentheses set `optIn.configStyleArguments = false` behind the scenes but now you have to explicitly add `optIn.configStyleArguments = false` to your config.

**Closed by olafurpg** 2016-10-23 14:38 UTC

**Comment by robbyki** [comment] 2017-11-28 12:44
I would like to achieve this as well but I'm not finding any good examples of how to format my ~/.scalafmt file. I'm using intellij with plugin. this is what I have tried but still not getting proper formatting with the classes params:
```
style = defaultWithAlign
maxColumn = 80
alignByOpenParenDefnSite = false
continuationIndentCallSite = 2
continuationIndentDefnSite = 2
alignByOpenParenCallSite = false
configStyleArguments = false
danglingParentheses = true
```
