### ISSUE TITLE
sbt plugin broken and intellij plugin does not find .scalafmt

### ISSUE THREAD

**Issue by hntd187** [olafurpg/scalafmt#362] opened 2016-07-05 21:05 UTC
I am trying to get scalafmt to work with my project, but I cannot get anything working.

when I run ```sbt -v scalafmt``` from the command line I get this

```
[info] Loading global plugins from /home/scarman/.sbt/0.13/plugins
[info] Loading project definition from /home/scarman/projects/ingestions/project
[info] Set current project to root (in build file:/home/scarman/projects/ingestions/)
[error] Unable to classload ScalaFmt, please file an issue:
[error] https://github.com/olafurpg/scalafmt/issues
[error] 
[error] URLs: 
[error] Version: 0.2.10
[error] Error: class java.lang.ClassNotFoundException
[error] Message: org.scalafmt.cli.Scalafmt210
[error] java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error] java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] java.lang.Class.forName0(Native Method)
[error] java.lang.Class.forName(Class.java:348)
[error] org.scalafmt.sbt.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(ReflectiveDynamicAccess.scala:38)
[error] org.scalafmt.sbt.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(ReflectiveDynamicAccess.scala:36)
[error] scala.util.Try$.apply(Try.scala:161)
[error] org.scalafmt.sbt.ReflectiveDynamicAccess.getClassFor(ReflectiveDynamicAccess.scala:36)
[error] org.scalafmt.sbt.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:66)
[error] org.scalafmt.sbt.ScalaFmtPlugin$.org$scalafmt$sbt$ScalaFmtPlugin$$getScalafmtLike(ScalaFmtPlugin.scala:115)
[error] org.scalafmt.sbt.ScalaFmtPlugin$$anonfun$configScalafmtSettings$4.apply(ScalaFmtPlugin.scala:97)
[error] org.scalafmt.sbt.ScalaFmtPlugin$$anonfun$configScalafmtSettings$4.apply(ScalaFmtPlugin.scala:94)
[error] scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[error] sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[error] sbt.std.Transform$$anon$4.work(System.scala:63)
[error] sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[error] sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[error] sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[error] sbt.Execute.work(Execute.scala:237)
[error] sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[error] sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[error] sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] java.lang.Thread.run(Thread.java:745)
[error] Unable to classload ScalaFmt, please file an issue:
[error] https://github.com/olafurpg/scalafmt/issues
[error] 
[error] URLs: 
[error] Version: 0.2.10
[error] Error: class java.lang.ClassNotFoundException
[error] Message: org.scalafmt.cli.Scalafmt210
[error] java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error] java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] java.lang.Class.forName0(Native Method)
[error] java.lang.Class.forName(Class.java:348)
[error] org.scalafmt.sbt.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(ReflectiveDynamicAccess.scala:38)
[error] org.scalafmt.sbt.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(ReflectiveDynamicAccess.scala:36)
[error] scala.util.Try$.apply(Try.scala:161)
[error] org.scalafmt.sbt.ReflectiveDynamicAccess.getClassFor(ReflectiveDynamicAccess.scala:36)
[error] org.scalafmt.sbt.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:66)
[error] org.scalafmt.sbt.ScalaFmtPlugin$.org$scalafmt$sbt$ScalaFmtPlugin$$getScalafmtLike(ScalaFmtPlugin.scala:115)
[error] org.scalafmt.sbt.ScalaFmtPlugin$$anonfun$configScalafmtSettings$4.apply(ScalaFmtPlugin.scala:97)
[error] org.scalafmt.sbt.ScalaFmtPlugin$$anonfun$configScalafmtSettings$4.apply(ScalaFmtPlugin.scala:94)
[error] scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[error] sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[error] sbt.std.Transform$$anon$4.work(System.scala:63)
[error] sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[error] sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[error] sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[error] sbt.Execute.work(Execute.scala:237)
[error] sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[error] sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[error] sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] java.lang.Thread.run(Thread.java:745)
[error] Unable to classload ScalaFmt, please file an issue:
[error] https://github.com/olafurpg/scalafmt/issues
[error] 
[error] URLs: 
[error] Version: 0.2.10
[error] Error: class java.lang.ClassNotFoundException
[error] Message: org.scalafmt.cli.Scalafmt210
[error] java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error] java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] java.lang.Class.forName0(Native Method)
[error] java.lang.Class.forName(Class.java:348)
[error] org.scalafmt.sbt.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(ReflectiveDynamicAccess.scala:38)
[error] org.scalafmt.sbt.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(ReflectiveDynamicAccess.scala:36)
[error] scala.util.Try$.apply(Try.scala:161)
[error] org.scalafmt.sbt.ReflectiveDynamicAccess.getClassFor(ReflectiveDynamicAccess.scala:36)
[error] org.scalafmt.sbt.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:66)
[error] org.scalafmt.sbt.ScalaFmtPlugin$.org$scalafmt$sbt$ScalaFmtPlugin$$getScalafmtLike(ScalaFmtPlugin.scala:115)
[error] org.scalafmt.sbt.ScalaFmtPlugin$$anonfun$configScalafmtSettings$4.apply(ScalaFmtPlugin.scala:97)
[error] org.scalafmt.sbt.ScalaFmtPlugin$$anonfun$configScalafmtSettings$4.apply(ScalaFmtPlugin.scala:94)
[error] scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[error] sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[error] sbt.std.Transform$$anon$4.work(System.scala:63)
[error] sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[error] sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[error] sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[error] sbt.Execute.work(Execute.scala:237)
[error] sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[error] sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[error] sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] java.lang.Thread.run(Thread.java:745)
```

Using:
* 0.2.10

.scalafmt in the root of my project
```
--style defaultWithAlign
--maxColumn 120
```

I tried the plugin in the global plugins, in my project plugins, adding it as a library dependency in my build and in my global plugins and nothing. I also cannot get the scalafmt intellij plugin to respect my .scalafmt 

```
lazy val scalafmtSettings = Seq(
  scalafmtConfig in ThisBuild := Some(file(".scalafmt"))
)
```

There is really nothing special or crazy in my build.

**Comment by olafurpg** [comment] 2016-07-05 23:07
It seems to be a dupe of #190, since "URLs: " is an empty string. For some reason, the SBT plugin doesn't seem to work if your build is an sbt plugin (`isPlugin := true`). Scalafmt doesn't compile against 2.10 so it needs to do some classloading hacks to work inside SBT, see https://gitter.im/olafurpg/scalafmt?at=573a3ce40cb634927f7f6c14

**Comment by hntd187** [comment] 2016-07-05 23:22
@olafurpg my build is not an sbt plugin.

**Comment by olafurpg** [comment] 2016-07-06 17:56
The root cause seems to be the same as in #190, nevertheless. I spent some time trying to track it down but with no luck.

**Comment by hntd187** [comment] 2016-07-06 18:57
Okay, is there anymore debugging I can provide to assist?

**Comment by olafurpg** [comment] 2016-07-06 19:00
Any easy to reproduce environment, like https://github.com/densh/sbt-plugin-scalafmt-failure

**Comment by hntd187** [comment] 2016-07-07 21:48
I believe I may have found the cause of this and a fix for it. I'm about to leave work, but I'll write more and hopefully verify my findings later tonight or tomorrow @olafurpg

**Comment by olafurpg** [comment] 2016-07-07 22:24
Exciting, looking forward to seeing what's the cause. I leave to West Africa tomorrow and will have sporadic satellite Internet for 16 days. I'll do my best to review but can't make any promises.

**Comment by olafurpg** [comment] 2016-07-28 08:01
Duplicate of #190, which I've found a fix for. Please open a separate ticket for the IntelliJ issue.

**Closed by olafurpg** 2016-07-28 08:01 UTC
