### ISSUE TITLE
Idempotency issue with 2.6.0

### ISSUE THREAD

**Issue by anna-zzz** [olafurpg/scalafmt#343] opened 2016-06-23 09:51 UTC
Scalafmt can't decide between these two:
```
    notFound.fold(HttpResponse(statusCode,
                               entity = jsonEntity("errors" → failuresList.map(_.description)))) {
      nf ⇒
        renderNotFoundFailure(nf)
    }
``` 
and 
```
    notFound.fold(
        HttpResponse(statusCode,
                     entity = jsonEntity("errors" → failuresList.map(_.description)))) { nf ⇒
      renderNotFoundFailure(nf)
    }
```

Version 2.6.0

```
$ cat .scalafmt
--style defaultWithAlign
--maxColumn 100
```

**Comment by olafurpg** [comment] 2016-06-23 10:00
Dupe of #339?

**Comment by anna-zzz** [comment] 2016-06-23 12:32
Well, feel free to close this one if you think it's a dupe :) I've got no idea

**Comment by olafurpg** [comment] 2016-06-23 12:58
I'm publishing right now 0.2.8 (skipping 0.2.7 because sonatype problems) that fixes this issue and decreases the number of non-idempotent cases in the test suite from 56 to 15. I'm heading to the airport in 1h and will be traveling, mostly offline, over the next few weeks. I will have very limited time to take a look to the remaining issues, so let's hope you don't bump into those 😜

**Closed by olafurpg** 2016-06-23 12:58 UTC

**Comment by anna-zzz** [comment] 2016-06-24 09:49
Looks like this one got fixed!
Enjoy your trip :)
