### ISSUE TITLE
Two open parens on one line screw up indentation

### ISSUE THREAD

**Issue by hseeberger** [olafurpg/scalafmt#325] opened 2016-06-20 07:04 UTC
Original:
```scala
mediator.expectMsg(PubSubMediator.Publish(
  className[MessageEvent],
  MessageAdded(`flowName`, Message("Akka rocks!", time))
))
```

Scalafmt:
```scala
mediator.expectMsg(PubSubMediator.Publish(
        className[MessageEvent],
        MessageAdded(`flowName`, Message("Akka rocks!", time))
    ))
```

I would like the input to look like this:
```scala
mediator.expectMsg(PubSubMediator.Publish(
    className[MessageEvent],
    MessageAdded(`flowName`, Message("Akka rocks!", time))
))
```

Using:
* 0.2.5
* --style defaultWithAlign --maxColumn 120 --spacesInImportCurlyBraces true --alignStripMarginStrings true

**Comment by olafurpg** [comment] 2016-06-20 08:57
I agree that scalafmt's output looks weird and the expected output looks better. The reason why the indentation is 8 spaces is because scalafmt bumps up the indentation for each `(` in a function application. This prevents confusing output like this


```scala
  Initialize(config(
    "port.http"),
    settings
  ))
```

where `settings` is at the same indentation as `"port.http"` but they are at different nesting levels. It appears that other formatters like clang-format special-case when there is only one argument. Scalafmt already does this for blocks wrapped in curly braces `{}` and could probably do the same with parentheses `()`.

**Comment by hseeberger** [comment] 2016-06-20 09:42
The example above looks pretty ugly to me: Shouldn't that be rewritten to the following anyway:

```
Initialize(
    config("port.http"),
    settings
)
```

**Comment by olafurpg** [comment] 2016-06-20 09:52
It was a synthetic example just to highlight what could happen when the indentation is inconsistent with the nesting level. Scalafmt would actually format it like this

```scala
Initialize(config("port.http"), settings)
```

The inconsistency won't be a problem when there is only one argument.

**Comment by joan38** [comment] 2016-06-22 11:00
I have:
```scala
  def map[B](f: A => B): AsyncValidation[E, B] =
    AsyncValidation(asyncValid map { valid =>
      valid.fold(
        error => Xor.Left(error),
        success => Xor.Right(f(success))
      )
    })
```

Scalafmted to:
```scala
  def map[B](f: A => B): AsyncValidation[E, B] =
    AsyncValidation(
      asyncValid map { valid =>
    valid.fold(
      error => Xor.Left(error),
      success => Xor.Right(f(success))
    )
  })
```

Do you think it's related to this issue?

**Comment by olafurpg** [comment] 2016-06-22 11:12
@joan38 On master branch that input produces:

```scala
def map[B](f: A => B): AsyncValidation[E, B] =
  AsyncValidation(asyncValid map { valid =>
    valid.fold(
        error => Xor.Left(error),
        success => Xor.Right(f(success))
    )
  })
```

I recommend you run from master branch or wait until 0.2.6 is released, which I hope to get out by tomorrow. A lot of bugs have been fixed since 0.2.5.

**Comment by joan38** [comment] 2016-06-22 11:14
@olafurpg you are awesome
Is there any way to run from master with SBT?
`addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "0.2.6-SNAPSHOT")` ?

**Comment by olafurpg** [comment] 2016-06-22 11:22
@joan38 https://gitter.im/olafurpg/scalafmt?at=576a4fe42554bbe049ba6ac8

**Comment by olafurpg** [comment] 2016-06-29 18:03
@hseeberger Using `--danglingParentheses true` and no align open parens now produces this output for your example in this issue. Releasing 0.2.9 soon.

```scala
mediator.expectMsg(
    PubSubMediator.Publish(
        className[MessageEvent],
        MessageAdded(
            `flowName`,
            Message(
                "Akka rocks!",
                time
            )
        )
    )
)

```

**Comment by hseeberger** [comment] 2016-06-30 17:13
Now other things are broken:

With 0.2.8:
``` scala
    Props(new Actor {
      context.stop(self)
      override def receive = Actor.emptyBehavior
    })
```
becomes with 0.2.9:
``` scala
    Props(
        new Actor {
      context.stop(self)
      override def receive = Actor.emptyBehavior
    }
    )
```

**Comment by olafurpg** [comment] 2016-06-30 19:33
Oh shoot, I forgot to exclude {} blocks. That's should be a simple fix, did you notice any other issues @hseeberger?

**Comment by olafurpg** [comment] 2016-06-30 19:47
I've fixed that example, if there's no other regression I can publish a quick release tonight. I leave for a 3 week vacation tomorrow morning 😄

**Comment by hseeberger** [comment] 2016-06-30 19:49
I have seen no other issue. Please publish and then have a good vacation! ;-)

**Comment by olafurpg** [comment] 2016-06-30 20:14
Released 0.2.10! Enjoy 😉

**Comment by hseeberger** [comment] 2016-06-30 20:17
Thanks!

**Comment by olafurpg** [comment] 2016-08-06 17:11
Is this still an issue @hseeberger? Here's the output on master:

```scala
// default style
mediator.expectMsg(
    PubSubMediator.Publish(
        className[MessageEvent],
        MessageAdded(`flowName`, Message("Akka rocks!", time))
    ))
// dangling parentheses
mediator.expectMsg(
    PubSubMediator.Publish(
        className[MessageEvent],
        MessageAdded(`flowName`, Message("Akka rocks!", time))
    )
)
```

Note that you can get the dangling parentheses layout with the default style if you insert a newline between the closing `))` in the end (i.e., opt into config style).

**Comment by hseeberger** [comment] 2016-08-07 18:44
No longer an issue. Thanks!

**Comment by olafurpg** [comment] 2016-08-07 19:10
Cool, closing then.

**Closed by olafurpg** 2016-08-07 19:10 UTC
